[project]
name = "beeai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11, <4.0"
dependencies = [
    "beeai-framework[wikipedia]>=0.1.29",
    "langchain-community>=0.3.27",
    "termcolor>=3.1.0",
    "wikipedia>=1.4.0",
]
